### ISSUE TITLE
GithubUtil 应该用static方法实现

### ISSUE THREAD

**Issue by iceBear67** [shaokeyibb/MinecraftServerDeployTool#10]
-

**Comment by shaokeyibb** [comment]
Kotlin你叫我怎么static嘛，难不成全都要@JvmStatic吗
再说不是要指定author和repo吗为啥静态

**Comment by iceBear67** [comment]
..好吧没注意就翻译成java来回答了
你应该用object才对（

**Comment by shaokeyibb** [comment]
object没法指定构造参数啊。。。

**Comment by iceBear67** [comment]
直接GithubUtil.xxx(原参数）啊

**Comment by iceBear67** [comment]
如果你的util有checkupdate之外的功能就可以考虑不这样

**Comment by shaokeyibb** [comment]
不是。。。你考虑一下我怎么指定用哪个仓库

**Comment by iceBear67** [comment]
好吧我的错。我刚刚看的时候只看到main.kt里的一种checkupd用法

**Comment by iceBear67** [comment]
可以close了
