### ISSUE TITLE
is not work!

### ISSUE THREAD

**Issue by Song-Xin233** [shaokeyibb/MinecraftServerDeployTool#18]
![image](https://user-images.githubusercontent.com/64391901/115117952-99ab7a80-9fd3-11eb-9827-201b7116633c.png)
windows10 21H1 X64
jre1.8u281 x64
akarin 1.16.2

**Comment by Song-Xin233** [comment]
![image](https://user-images.githubusercontent.com/64391901/115118012-e4c58d80-9fd3-11eb-8923-0483b586e7bc.png)
选择paper也有一样的问题awa

**Comment by Song-Xin233** [comment]
![image](https://user-images.githubusercontent.com/64391901/115118046-03c41f80-9fd4-11eb-8cab-f142a073d6e0.png)
this is choose the paper server, and all options are default

**Comment by shaokeyibb** [comment]
for akain,it's because the Akarin CI change their address,and now have been fixed since #19 
for paper,maybe please type the build version manually

**Comment by Song-Xin233** [comment]
It is recommended to catch and handle the exception next time :)
