### ISSUE TITLE
[Bug] 服务端无法启动

### ISSUE THREAD

**Issue by WTP016-CN** [shaokeyibb/MinecraftServerDeployTool#8]
如题目，**~~屑贺兰~~**写的工具果然很屑
**下方为运行全过程**
![首次运行图](https://i.loli.net/2020/09/06/QuA7H1mlVhM9ers.png) 首次运行图
![image.png](https://i.loli.net/2020/09/06/HONPKCpAMsE9vxq.png) 服务端选择Akarin
![image.png](https://i.loli.net/2020/09/06/dWZS7AyJHtj364h.png) 部署出现错误

**Comment by shaokeyibb** [comment]
估计是Akarin改他们CI了
懒得改说实话

**Comment by WTP016-CN** [comment]
> 估计是Akarin改他们CI了
> 懒得改说实话

屑贺兰屑贺兰屑贺兰（（（
